### ISSUE TITLE
hi,we need your demo

### ISSUE THREAD

**Issue by introspection3** [pamidur/fluent-il#1]
(another  question :did you use AsyncLocal<T>, is it safe? can it  free memory  when thread stoped>)

**Comment by pamidur** [comment]
Hi @564064202 idk how, but this issue went unnoticed for almost a year. Maybe I didn't except issues here. Anyway I'm sorry I didn't answer earlier.

As to your question, no I don't use AsyncLocal in this project and other projects too. So I honestly don't know about it's safety

**Comment by pamidur** [comment]
Please feel free to reopen issue if needed
